export const sections = [
  { name: "notice", label: "Notice" },
  { name: "user", label: "User" },
  { name: "towers", label: "Towers" },
  { name: "monsters", label: "Wolfs" },
  { name: "monster-skills", label: "Monster Skills" },
  { name: "monster-calc", label: "Wolf Calculation" },
  { name: "umaps", label: "Umaps" },
  { name: "umap-detail", label: "Umap Detail" },
  { name: "umap-design", label: "Umap Design" },
  { name: "dmaps", label: "Dream Maps" },
  { name: "dmap-detail", label: "Dream Map Detail" },
  { name: "baoxiang", label: "Baoxiang Properties" },
  { name: "dream-design", label: "Dream Design" },
  { name: "tower-design", label: "Tower Design" },
];
