import data from "@/assets/sys_config.json";
import lang from "@/assets/string_cn.xml?raw";
import _ from "lodash-es";
import { isAlpha, compareNumber } from "@/utils";
import X2JS from "x2js";
import { GlobalDataGetValue } from "./GlobalDataGetValue";

export class GlobalData {
  public static $Maps: any[];
  public static $_free_gift_close_pf: string = "";
  public static $_tools_no_use: string;
  public static $_version: string = "";
  public static $_urlMain: string = "";
  public static $_urlXMLFile: string = "";
  public static $_urlGateway: string = "";
  public static $_urlMaterial: string = "";
  public static $_gameLanguage: string = "";
  public static readonly $_gameFloor: string = "xingcloud";
  public static $_snsId: string = "";
  public static $_referer: string = "";
  public static $_lang: string = "";
  public static $_xc_publish: string = "";
  public static $_xc_baseURL: string = "";
  public static $_initURLXML: string = "";
  public static $_sessionname: string = "";
  public static $_where: string = "";
  public static $_sessionvalue: string = "";
  public static $_gateway_key: string = "";
  public static $_help_url: string = "";
  public static $_currCardId: string = "";
  public static $_GAME_uid: string;
  public static $_GAME_fid: string;
  public static $_GAME_fid_temp: string;
  public static $_user_explev: any = {};
  public static $_user_power: any = {};
  public static $_user_level_max: int;
  public static $_user_default_headurl: string;
  public static $_global_language_str: any = null;
  public static $_global_dataProfile_txt: any = null;
  public static $_global_mixtrue_gem: int = 500;
  public static $_global_gold_remind: number = 5000;
  public static $_global_population_remind: number = 1.5;
  public static $_global_speedup_level: int = 0;
  public static $_mapBaseDataArr_Obj: any;
  public static $_mapAtt_Obj: any;
  public static $_wolfAtt_Obj: any;
  public static $_towerAtt_Obj: any;
  public static $_normal_towerAtt_Obj: any;
  public static $_wallAtt_Obj: any;
  public static $_normal_wallAtt_Obj: any;
  public static $_barrierAtt_Obj: any;
  public static $_bulletAtt_Obj: any;
  public static $_bombAtt_Obj: any;
  public static $_roadblockAtt_Obj: any;
  public static $_shop_embed: any[] = [];
  public static $_shop_used: any[] = [];
  public static $_shop_snarp: any[] = [];
  public static $_shop_wc: any[] = [];
  public static $_shop_tame: any[] = [];
  public static $_exchange_properties: any;
  public static $_exchange_all: any[] = [];
  public static $_exchange_now: any[] = [];
  public static $_build_data_tower: any[] = [];
  public static $_build_data_stageStyle: any[] = [];
  public static $_tools_data_embed: any[] = [];
  public static $_tools_data_trap: any[] = [];
  public static $_tools_data_used: any[] = [];
  public static $_tools_data_tame: any[] = [];
  public static $_tools_data_wc: any[] = [];
  public static $_tools_data_wolfs: any[] = [];
  public static $_game_ing_auto: int = 0;
  public static $_stageWidth: number;
  public static $_stageHeight: number;
  public static $_stageTag: Boolean = false;
  public static $_stageXV: number = 0;
  public static $_log_friend_group: any[];
  public static $_log_system_group: any[];
  public static $_log_group: any[];
  public static $_global_properties: any = {};
  public static $_global_msg_temp: any;
  public static $_global_broadcast_templates: any;
  public static g_global_properties_myDataNum: any;
  public static m_global_properties_myDataNum: any;
  public static $_global_properties_myData: any = {};
  public static $_global_systemMsg: any = {};
  public static $_global_slave_npcData: any = {};
  public static g_global_slave_myData: any = {};
  public static m_global_slave_myData: any = {};
  public static $_slave_canUse: any[] = [];
  public static $_global_slave_myDataArr: any[];
  public static $_user_default_name: string;
  public static $_slave_catch_time: int;
  public static $_slave_full_time: int;
  public static $_slave_sleep_time: int;
  public static $_slave_cold_time: int;
  public static $_slave_max_invite_score: any = null;
  public static $_comfort_slave_coin: int = 0;
  public static $_slave_friend_price: int = 7;
  public static $_slave_friend_free_price: number = 0.1;
  public static $_24H_second: int = 86400;
  public static $_slave_build_max: any;
  public static $_gift_receive_max: int;
  public static $_gift_send_max: int;
  public static $_gift_send_person_max: int = 20;
  public static $_skillAtt_Obj: any;
  public static $_skillPackage_Obj: any;
  public static $_map_Obj: any;
  public static $_wave_hard_Obj: any;
  public static g_userLevelData: any;
  public static m_userLevelData: any;
  public static $_friendLevelData: any;
  public static $_sell_building_dis: number;
  public static $_task_Obj: any;
  public static $_level_up_gift: any;
  public static $_pass_map_gift: any;
  public static $_install_gift: any;
  public static $_mixture_gem: any;
  public static $_mixture_gem_dream: any;
  public static $_mixture_gem_num: int = 0;
  public static $_mixture_gem_dream_num: int = 0;
  public static $_user_task: any;
  public static $_feed_gift: any;
  public static $_request_gift: any;
  public static $_request_id_list: any[];
  public static $_get_broadcast_time: int;
  public static $_get_system_broadcast_time: int;
  public static $_get_global_broadcast_time: int;
  public static $_system_broadcast_broadcast_time: int;
  public static $_system_broadcast_rebroadcast_time: int;
  public static $_loginEveryDayAwardB: Boolean = false;
  public static $_loginEveryDayAward: any = null;
  public static $_isFanB: Boolean = false;
  public static $_isFan_gift: any = null;
  public static $_everyday_gift: any[];
  public static $_stealWolfFalseNum: number = 0;
  public static $_buyFriendFalseNum: number = 0;
  public static $_lured_wolf_max: int = 0;
  public static $_lured_wolf_level: int = 0;
  public static $_is_super: Boolean;
  public static $_is_speedup: Boolean = true;
  public static $_visitFriendList_static: any[];
  public static $_visitFriendListMax: int;
  public static $_visitFriendAwardNum: any[];
  public static $_dalic_TimeOver: number;
  public static $_dalic_valueArr: any[];
  public static $_dalic_value: int;
  public static $_dalic_userTimeNum: int;
  public static $_user_taskAll: any;
  public static $_isDream: Boolean = false;
  public static $_isFirstIntoDream: Boolean = false;
  public static $_bagDream: Boolean = false;
  public static $_goldDream: int = 0;
  public static $_isTheirsDream: Boolean = false;
  public static $_theDreamListData: any = null;
  public static $_qq_isGetNewbieAward: int = 1;
  public static $_qq_isGetEveryAward: int = 1;
  public static $_qq_sell: number = 0.8;
  public static $_qq_vip_url: string;
  public static $_qqUpgrade_award: any;
  public static $_qq_vip_gift: any;
  public static $_dream_tower: any;
  public static $_dream_wall: any;
  public static $_dream_gift: any;
  public static $_dream_opt_cfg: any;
  public static $_dream_wolf_hard_ness: any;
  public static $_dream_map: any;
  public static $_dream_userLevelData: any;
  public static $_dream_friendLevelData: any;
  public static $_dream_active_time: any;
  public static $_dream_active_dsort: any[];
  public static $_user_reward: any[];
  public static $_show_limit: int;
  public static $_top_limit: int;
  public static $_currStageStatus: int = 0;
  public static $_currStageStatus_pk: string = "";
  public static $_currStageStatus_pk_ffid: string = "";
  public static $_currStageChangeStatusB: Boolean = false;
  public static $_year_active_gift: any;
  public static $_active_draw_gift: any;
  public static $_friends_not_login_time: Date;
  public static g_global_camp_obj: any;
  public static m_global_camp_obj: any;
  public static $_global_freeGift: any[];
  public static $_global_freeGiftObj: any;
  public static $_global_freeGift_timeMax: number;
  public static g_global_camp_wolfs: any;
  public static m_global_camp_wolfs: any;
  public static $_global_camp_obj_f: any;
  public static $_global_camp_wolfs_f: any;
  public static $_wolfs_unlock_lv: any[];
  public static $_wolfs_unlock_gold: any[];
  public static $_wolfs_unlock_properties: any[];
  public static $_wolfs_unlock_max: int;
  public static $_camp_wolf_max_need_coin: int;
  public static $_camp_wolfs_pk_arr: any[];
  public static $_camp_hold_time: int;
  public static $_camp_pk_cd_time: int;
  public static $_camp_pk_times_max: int;
  public static $_camp_defend_times_max: int;
  public static $_camp_pk_arena_times_max: int;
  public static $_camp_defend_arena_times_max: int;
  public static $_camp_need_user_level: int;
  public static $_camp_arena_need_user_level: int;
  public static $_pk_catena_win_times: int;
  public static $_defend_catena_win_times: int;
  public static $_camp_mining_rate: any;
  public static $_camp_sell_building_dis: number;
  public static $_camp_use_exp_wolf_max: int;
  public static $_camp_use_exp_tower_max: int;
  public static $_camp_wolf_lv_max: int;
  public static $_camp_create_mine_help_max: int = 3;
  public static $_camp_create_mine_help_friends_num: int = 3;
  public static $_camp_create_mine_help_reduce_time: int = 60;
  public static $_tower_worth_factor: any[];
  public static $_wolf_worth_factor: any[];
  public static $_defend_map_snarp_max: int;
  public static $_defend_succ_factor: number;
  public static $_defend_failed_factor: number;
  public static $_defend_arena_succ_factor: number;
  public static $_defend_arena_failed_factor: number;
  public static $_conflict_skill_kind: any[];
  public static $_skill_lvup_spend: any;
  public static $_skill_grade_score: any;
  public static $_is_guide: Boolean;
  public static $_is_guide_true: Boolean;
  public static $_user_guide: any;
  public static $_can_guide: Boolean = false;
  public static $_hold_exp_need_seconds: number = 0;
  public static $_rare_item_url: string;
  public static $_rare_item_name: string;
  public static $_rare_item_coin: int;
  public static $_rare_item_invite_score: int;
  public static $_costcoin: any;
  public static $_diaorenwenshu: Boolean = false;
  public static $_online_gift: any;
  public static $_user_online_gift: any;
  public static $_qq_vip_gift_only: any = {};
  public static $_possword_gift: any;
  public static $_conveyer_speed: int;
  public static $_upgrade_3366: any = {};
  public static $_gameMode: int;

  public static umapsById: [string, any][];
}

(function () {
  const x2js = new X2JS();
  GlobalData.$_global_language_str = x2js.xml2dom(lang);

  GlobalData.$_global_properties = data.properties;
  GlobalDataGetValue.addObjAttribute_type_id(GlobalData.$_global_properties);
  GlobalData.$_skillAtt_Obj = data.skill;
  GlobalDataGetValue.addObjAttribute_type_id(GlobalData.$_skillAtt_Obj);
  GlobalData.$_skillPackage_Obj = data.skill_package;
  GlobalData.$_map_Obj = data.umaps;
  GlobalData.$_tower_worth_factor = data["camp_system_simple"]["tower_worth_factor"];
  GlobalData.$_wolf_worth_factor = data["camp_system_simple"]["wolf_worth_factor"];
  GlobalData.$_towerAtt_Obj = data.building.tower;
  GlobalData.$_bulletAtt_Obj = data.bullet;
  GlobalData.$_wolfAtt_Obj = data.wolfs;
  GlobalData.$_wallAtt_Obj = data.building["wall"];
  GlobalData.$_barrierAtt_Obj = data.barrier;
  GlobalData.$_level_up_gift = data.level_up_gift;
  GlobalData.$_pass_map_gift = data.pass_map_gift;
  GlobalData.$Maps = data["version_ctrl"]["Maps"];

  let _pvp = data["camp_system_simple"];
  if (_pvp) {
    GlobalData.$_wolfs_unlock_lv = _pvp["camp_wolf_lv_max_factor"];
    GlobalData.$_wolfs_unlock_gold = _pvp["camp_wolf_gold_max_factor"];
    // GlobalData.$_wolfs_unlock_properties = _pvp["camp_wolf_properties_max_factor"];
    GlobalData.$_camp_hold_time = _pvp["hold_time"];
    GlobalData.$_camp_pk_cd_time = _pvp["pk_cd_time"];
    GlobalData.$_camp_pk_times_max = _pvp["pk_times_max"];
    GlobalData.$_camp_defend_times_max = _pvp["defend_times_max"];
    GlobalData.$_camp_pk_arena_times_max = _pvp["pk_arena_times_max"];
    GlobalData.$_camp_defend_arena_times_max = _pvp["defend_arena_times_max"];
    GlobalData.$_camp_mining_rate = _pvp["mine_rate"];
    GlobalData.$_camp_sell_building_dis = _pvp["sell_building_dis"];
    GlobalData.$_tower_worth_factor = _pvp["tower_worth_factor"];
    GlobalData.$_wolf_worth_factor = _pvp["wolf_worth_factor"];
    GlobalData.$_defend_map_snarp_max = _pvp["defend_map_snarp_max"];
    GlobalData.$_defend_succ_factor = _pvp["defend_succ_factor"];
    GlobalData.$_defend_failed_factor = _pvp["defend_failed_factor"];
    GlobalData.$_defend_arena_succ_factor = _pvp["defend_arena_succ_factor"];
    GlobalData.$_defend_arena_failed_factor = _pvp["defend_arena_failed_factor"];
    GlobalData.$_conflict_skill_kind = _pvp["conflict_skill_kind"];
    GlobalData.$_skill_lvup_spend = _pvp["skill_lvup_spend"];
    GlobalData.$_skill_grade_score = _pvp["skill_grade_score"];
    GlobalData.$_camp_use_exp_wolf_max = _pvp["use_exp_wolf_max"];
    GlobalData.$_camp_use_exp_tower_max = _pvp["use_exp_tower_max"];
    GlobalData.$_camp_wolf_lv_max = _pvp["wolf_lv_max"];
    GlobalData.$_camp_need_user_level = _pvp["camp_need_user_level"];
    GlobalData.$_camp_arena_need_user_level = _pvp["arena_need_user_level"];
    GlobalData.$_camp_create_mine_help_max = _pvp["create_mine_help_max"];
    GlobalData.$_camp_create_mine_help_friends_num = _pvp["create_mine_help_friends_num"];
    // GlobalData.$_camp_create_mine_help_reduce_time = _pvp["create_mine_help_reduce_time"];
  }

  const sortedIds = Object.keys(data.umaps).sort((k1, k2) =>
    compareNumber(
      parseInt(/(?<=m).+(?=[A-Z]*)/.exec(isAlpha(k1[-1]) ? k1 : k1 + "A")![0], 36),
      parseInt(/(?<=m).+(?=[A-Z]*)/.exec(isAlpha(k2[-1]) ? k2 : k2 + "A")![0], 36)
    )
  );
  GlobalData.umapsById = sortedIds.map(k => [k, data.umaps[k]]);

  console.log(GlobalData.umapsById);
  console.log("init");
})();
